### ISSUE TITLE
Doesn't succeed in getting session from the server during Initial Setup

### ISSUE THREAD

**Issue by jacob2020baklas** [go-shiori/shiori-web-ext#61]
when setting up the extension @latest in firefox it gives a 404 not found status 
the server works fine behind a proxy

**Comment by fmartingr** [comment]
Are you also using a Shiori build from the `master` branch? (1.6.0-dev)

**Comment by CLKRUN** [comment]
> Are you also using a Shiori build from the `master` branch? (1.6.0-dev)

Same issue in ungoggled chromium. ''Error: 404 page not found''

**Comment by OPerepadia** [comment]
It appears that this bug has already been fixed in the master branch.
I tried building the extension myself and was able to login. But because the extension is not signed, I have to load it using the "Load Temporary Add-on" each time after restarting the browser
Do you have an estimate on when we can expect the new release with the signed extension? Thanks!

**Comment by teishahbc** [comment]
Same here

**Comment by teishahbc** [comment]
> Same here

Nevermind! I found i used a old docker image from a older source radhifadlillah/shiori and the latest is ghcr.io/go-shiori/shiori, after shifting and everything is fine now!

**Comment by fmartingr** [comment]
Redirecting this issue to #72, since the real issue is maintaining the addon/server in sync and up to date.
